#!/usr/bin/env python3
"""
html-sbeam.py
Processes solar panel data from daily logs (YY-MM-DD.CSV) to compile monthly logs (_YYYY-MM.CSV),
then generates a color-coded HTML webpage showing solar panel kWh production.
Supports configuration via html-sbeam.rc file and detects logging anomalies.
"""

import os
import sys
import glob
import re
import argparse
import shutil
import json
from datetime import datetime
from pathlib import Path
import socket


# Programma details voor de footer
PGM = "html-sbeam"
VERSION = "(07-07-2026 12:05)"

# === START FOOTER DEFINITIE ===
# Bepaal OS en hostname voor de footer
try:
    _hostname = socket.gethostname().split(".")[0]
except Exception:
    _hostname = ""
_os_naam = "Windows" if sys.platform == "win32" else "Linux"

_default_footer = f"Generated by ${{PGM}} v${{VER}} ({_os_naam})"
if sys.platform != "win32":
    _default_footer += f" at {_hostname}"
# === END FOOTER DEFINITIE ===

# Force UTF-8 output to prevent issues on Windows console with special characters
if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

# Configuration defaults
DEFAULTS = {
    "INPUT_DIR": r"Z:\DATA\SBEAM",
    "OUTPUT_DIR": r"Z:\WWW\domains\www.agrarix.net\pages\sbeam",
    "INDEX_FILE": "index.html",
    "LOG_FILE": "html-sbeam.log",
    "VERSION": "(07-07-2026 12:05)",
    "FFACE": "verdana",
    "FSIZE": "6",
    "HOSTNAME": "xynix",
    "SIZE_MOBILE": "0.9em",
    "SIZE_DESKTOP": "1.25em",
    "TITLE": "Zonnepanelen opbrengst op CHL14 (mbv SunnyBEAM)",
    "ICON": "solar_pingu.jpg",
    "FOOTER": "Generated by (Agrarix)${PGM} v${VER} (${OS}) ${DATE} ${TIME}"
}

SCRIPT_DIR = Path(__file__).parent
WARNINGS = []

def parse_args():
    """Parse command line arguments"""
    # Windows-style /help and /? mapping
    for i, arg in enumerate(sys.argv):
        if arg.lower() in ("/help", "/?", "?"):
            sys.argv[i] = "--help"
            
    parser = argparse.ArgumentParser(
        prog="html-sbeam",
        description="Generates a static color-coded HTML page from SunnyBeam solar data CSV files."
    )
    parser.add_argument(
        "-c", "--config",
        default="html-sbeam.rc",
        help="Pad naar het configuratiebestand (standaard: %(default)s)"
    )
    parser.add_argument(
        "-d", "--days",
        action="store_true",
        help="Alleen dagbestanden naar maandbestanden compileren (geen HTML genereren)"
    )
    parser.add_argument(
        "-p", "--proc", "-w", "--www",
        action="store_true",
        dest="proc_only",
        help="Alleen HTML-pagina genereren op basis van bestaande maandbestanden (geen dagbestanden compileren)"
    )
    parser.add_argument(
        "-f", "--filter",
        default="",
        help="Filter om alleen bestanden te verwerken die deze tekst bevatten (bijv. een specifiek jaar)"
    )
    parser.add_argument(
        "-j", "--json",
        action="store_true",
        dest="generate_json",
        help="Dagbestanden (YY-MM-DD.CSV) verwerken naar JSON-bestanden in de map 'daily'"
    )
    parser.add_argument(
        "-V", "--version",
        action="store_true",
        help="Toon het versienummer en build-informatie"
    )
    parser.add_argument(
        "config_file",
        nargs="?",
        default=None,
        help="Positioneel pad naar configuratiebestand (voor backwards compatibility)"
    )
    return parser.parse_args()

def load_config(config_path_str):
    """Load configuration from .rc file with key=\"value\" syntax"""
    cfg = DEFAULTS.copy()
    config_file = Path(config_path_str)
    
    if not config_file.is_absolute():
        if sys.platform != "win32":
            # On Linux, look in ~/etc/
            config_file = Path.home() / "etc" / config_path_str
        else:
            # On Windows, look in the script's directory
            config_file = SCRIPT_DIR / config_file
            
    if not config_file.exists():
        print(f"Informatie: {config_file.name} niet gevonden, standaardwaarden worden gebruikt.")
        return cfg
        
    print(f"Configuratie geladen uit: {config_file}")
    try:
        with open(config_file, "r", encoding="utf-8", errors="ignore") as f:
            for line in f:
                line = line.strip()
                if not line or line.startswith("#"):
                    continue
                if "=" in line:
                    key, val = line.split("=", 1)
                    key = key.strip()
                    val = val.strip()
                    # Strip comments on the same line
                    if "#" in val:
                        parts = val.split("#", 1)
                        if parts[0].count('"') % 2 == 0 and parts[0].count("'") % 2 == 0:
                            val = parts[0].strip()
                    # Strip outer quotes
                    if (val.startswith('"') and val.endswith('"')) or (val.startswith("'") and val.endswith("'")):
                        val = val[1:-1]
                    cfg[key] = val
        return cfg
    except Exception as e:
        print(f"Fout bij het laden van {config_file.name}: {e}")
        return cfg

def parse_daily_file(fpath):
    """
    Parses a daily YY-MM-DD.CSV file.
    If E-Today is missing or invalid, calculates it from 10-minute power values.
    Returns (e_total_str, e_today_str)
    """
    e_today = "-"
    e_total = "-"
    try:
        with open(fpath, "r", encoding="utf-8", errors="ignore") as f:
            lines = [line.strip() for line in f]
            
        for line in lines:
            if line.startswith("E-Today kWh;"):
                e_today = line.split(";", 1)[1].strip()
            elif line.startswith("E-Total kWh;"):
                e_total = line.split(";", 1)[1].strip()
                
        # Check if E-Today is missing or invalid
        if e_today in ("-", "-,---", ""):
            powers = []
            for line in lines:
                if ";" in line:
                    parts = line.split(";")
                    if len(parts) >= 2 and re.match(r"^\d{2}:\d{2}$", parts[0].strip()):
                        val_str = parts[1].strip()
                        if val_str != "-,---" and val_str != "":
                            try:
                                powers.append(float(val_str.replace(",", ".")))
                            except ValueError:
                                pass
            if powers:
                # Calculate energy: Sum(Power in kW) * (10 / 60) hours
                calc_today = sum(powers) / 6.0
                e_today = f"{calc_today:.3f}".replace(".", ",")
                msg = f"WARNING: E-Today was leeg in {os.path.basename(fpath)}. Berekend uit 10-minuten waarden: {e_today} kWh"
                WARNINGS.append(msg)
    except Exception as e:
        pass
    return e_total, e_today

def parse_daily_file_timeseries(fpath):
    """
    Parses a daily YY-MM-DD.CSV file to extract 10-minute interval readings.
    """
    labels = []
    data = []
    try:
        with open(fpath, "r", encoding="utf-8", errors="ignore") as f:
            for line in f:
                if ";" in line:
                    parts = line.split(";")
                    if len(parts) >= 2 and re.match(r"^\d{2}:\d{2}$", parts[0].strip()):
                        time_str = parts[0].strip()
                        val_str = parts[1].strip()
                        if val_str not in ("-,---", "", "-"):
                            try:
                                val = float(val_str.replace(",", "."))
                                # Filter out large anomalies
                                if val <= 50.0:
                                    labels.append(time_str)
                                    data.append(round(val, 3))
                            except ValueError:
                                pass
    except Exception:
        pass
    return labels, data

def generate_daily_json_files(input_dir, output_dir, log_func, all_files=False):
    """
    Scans for YY-MM-DD.CSV files and generates compact JSON files under output_dir/daily/
    By default, only checks/compiles the last 5 chronological day files for performance.
    Calculates and stores the global max power in max_power.txt.
    """
    daily_dir = os.path.join(output_dir, "daily")
    os.makedirs(daily_dir, exist_ok=True)
    
    daily_files = sorted(glob.glob(os.path.join(input_dir, "[0-9][0-9]-[0-9][0-9]-[0-9][0-9].CSV")))
    if not daily_files:
        return
        
    if not all_files:
        # Enkel de laatste 5 bestanden controleren/verwerken om I/O te minimaliseren
        files_to_process = daily_files[-5:]
        log_func("Controleren van de meest recente dagbestanden...")
    else:
        files_to_process = daily_files
        log_func("Genereren van alle dagelijkse JSON-bestanden voor de grafiek...")
        
    # Laad max vermogen uit cache bestand
    max_power_path = os.path.join(daily_dir, "max_power.txt")
    global_max_power = 0.0
    if os.path.exists(max_power_path):
        try:
            with open(max_power_path, "r", encoding="utf-8") as f:
                global_max_power = float(f.read().strip())
        except Exception:
            pass
            
    max_power_changed = False
    
    # Bepaal de actieve periodes (huidige en vorige maand) die nog gewijzigd kunnen worden (alleen relevant voor all_files=True)
    now = datetime.now()
    current_year = now.year
    current_month = now.month
    
    active_periods = []
    active_periods.append(f"{current_year}-{current_month:02d}")
    
    prev_month = current_month - 1 if current_month > 1 else 12
    prev_year = current_year if current_month > 1 else current_year - 1
    active_periods.append(f"{prev_year}-{prev_month:02d}")
    
    for fpath in files_to_process:
        fname = os.path.basename(fpath)
        m = re.match(r"^(\d{2})-(\d{2})-(\d{2})\.CSV$", fname)
        if not m:
            continue
        yy, mm, dd = m.groups()
        year = f"20{yy}"
        
        target_json = os.path.join(daily_dir, f"{year}-{mm}-{dd}.json")
        
        # Check if we need to regenerate
        recreate = True
        if os.path.exists(target_json):
            period = f"{year}-{mm}"
            # Als we niet alle bestanden verwerken, controleren we altijd de mtime van de geselecteerde bestanden
            if not all_files or period in active_periods:
                mtime_csv = os.path.getmtime(fpath)
                mtime_json = os.path.getmtime(target_json)
                if mtime_json > mtime_csv:
                    recreate = False
            else:
                recreate = False
                
        if recreate:
            labels, data = parse_daily_file_timeseries(fpath)
            if labels:
                try:
                    with open(target_json, "w", encoding="utf-8") as f:
                        json.dump({"labels": labels, "data": data}, f)
                    log_func(f"  JSON aangemaakt: {os.path.basename(target_json)}")
                except Exception as e:
                    log_func(f"  Fout bij schrijven naar {os.path.basename(target_json)}: {e}")
                
                # Update max vermogen
                if data:
                    file_max = max(data)
                    if file_max > global_max_power:
                        global_max_power = file_max
                        max_power_changed = True
                        
    # Eenmalige scan van alle bestaande JSON's als de cache nog op 0 staat
    if global_max_power == 0.0:
        log_func("Eenmalige scan om maximale vermogen over alle JSON-bestanden te bepalen...")
        for fp in daily_files:
            fname = os.path.basename(fp)
            m = re.match(r"^(\d{2})-(\d{2})-(\d{2})\.CSV$", fname)
            if not m:
                continue
            yy, mm, dd = m.groups()
            year = f"20{yy}"
            t_json = os.path.join(daily_dir, f"{year}-{mm}-{dd}.json")
            if os.path.exists(t_json):
                try:
                    with open(t_json, "r", encoding="utf-8") as f:
                        js_data = json.load(f)
                        vals = js_data.get("data", [])
                        if vals:
                            file_max = max(vals)
                            if file_max > global_max_power:
                                global_max_power = file_max
                                max_power_changed = True
                except Exception:
                    pass
                    
    # Sla het maximale vermogen op als dit veranderd is en groter is dan 0.0
    if global_max_power > 0.0 and (max_power_changed or not os.path.exists(max_power_path)):
        try:
            with open(max_power_path, "w", encoding="utf-8") as f:
                f.write(f"{global_max_power:.3f}")
        except Exception as e:
            log_func(f"  Fout bij schrijven naar max_power.txt: {e}")





def compile_monthly_files(input_dir, log_func, file_filter=""):

    """
    Compiles daily YY-MM-DD.CSV files into monthly _YYYY-MM.CSV files.
    Skips compilation if the monthly file already exists.
    """
    log_func("Compileren van maandelijkse bestanden uit dagelijkse logs...")
    daily_files = glob.glob(os.path.join(input_dir, "[0-9][0-9]-[0-9][0-9]-[0-9][0-9].CSV"))
    
    # Group daily files by 20YY-MM
    groups = {}
    for fpath in daily_files:
        fname = os.path.basename(fpath)
        m = re.match(r"^(\d{2})-(\d{2})-(\d{2})\.CSV$", fname)
        if not m:
            continue
        yy, mm, dd = m.groups()
        month_key = f"20{yy}-{mm}"
        
        # Apply filter on month_key or filename
        if file_filter and (file_filter not in month_key and file_filter not in fname):
            continue
            
        if month_key not in groups:
            groups[month_key] = []
        groups[month_key].append((dd, fpath))
        
    for month_key, items in sorted(groups.items()):
        target_file = os.path.join(input_dir, f"_{month_key}.CSV")
        raw_monthly_file = os.path.join(input_dir, f"{month_key}.CSV")
        
        recreate = False
        if os.path.exists(target_file):
            if os.path.exists(raw_monthly_file):
                mtime_raw = os.path.getmtime(raw_monthly_file)
                mtime_target = os.path.getmtime(target_file)
                if mtime_raw > mtime_target:
                    recreate = True
                    log_func(f"  {month_key}.CSV is nieuwer dan _{month_key}.CSV. _{month_key}.CSV wordt opnieuw aangemaakt.")
            
            if not recreate:
                log_func(f"  _{month_key}.CSV bestaat al. Overslaan.")
                continue
            
        log_func(f"  Maandbestand aanmaken: _{month_key}.CSV uit {len(items)} dagbestanden...")
        
        # Sort items by day
        items.sort(key=lambda x: x[0])
        
        rows = []
        rows.append("sep=;")
        rows.append("Time;E-Total;E-Today")
        rows.append("DD-MM-YYYY;kWh;kWh")
        
        for dd, fpath in items:
            yy, mm = month_key[2:4], month_key[5:7]
            date_str = f"{dd}-{mm}-20{yy}"
            e_total, e_today = parse_daily_file(fpath)
            rows.append(f"{date_str};{e_total};{e_today}")
            
        try:
            with open(target_file, "w", encoding="utf-8") as f:
                f.write("\n".join(rows) + "\n")
        except Exception as e:
            log_func(f"  Fout bij het schrijven van _{month_key}.CSV: {e}")

def parse_csv_file(fpath):
    """
    Parses a compiled _YYYY-MM.CSV file (or YYYY-MM.CSV fallback).
    Returns a list of tuples: (date_str, e_total_float, e_today_float)
    """
    data = []
    try:
        with open(fpath, "r", encoding="utf-8", errors="ignore") as f:
            for line in f:
                if ";" not in line:
                    continue
                parts = line.strip().split(";")
                if len(parts) < 3:
                    continue
                date_str = parts[0].strip()
                # Match DD-MM-YYYY date format
                if not re.match(r"^\d{2}-\d{2}-\d{4}$", date_str):
                    continue
                
                tot_str = parts[1].strip()
                tod_str = parts[2].strip()
                
                # Check for empty or invalid readings
                if tot_str == "" or tot_str == "-,---" or tod_str == "" or tod_str == "-,---" or tot_str == "-" or tod_str == "-":
                    continue
                
                try:
                    tot = float(tot_str.replace(",", "."))
                    tod = float(tod_str.replace(",", "."))
                    data.append((date_str, tot, tod))
                except ValueError:
                    pass
    except Exception as e:
        print(f"Fout bij het lezen van {os.path.basename(fpath)}: {e}")
    return data

def calculate_monthly_production(data_rows, filename, is_current_month):
    """
    Calculates monthly production and detects anomalies.
    """
    # Filter rows where e_total is greater than 0
    valid_rows = [r for r in data_rows if r[1] > 0]
    if not valid_rows:
        msg = f"WARNING: Geen geldige metingen gevonden in {filename}"
        WARNINGS.append(msg)
        return None, None, False
        
    # Check for anomalies (resets or daily jumps > 50 kWh)
    has_anomaly = False
    for i, (date_str, tot, tod) in enumerate(valid_rows):
        if tod > 50.0:
            msg = f"WARNING: Anomalie gedetecteerd in {filename} op {date_str}: E-Today is {tod} kWh (sprong genegeerd)"
            WARNINGS.append(msg)
            has_anomaly = True
            
    # Check completeness (less than 25 days of data)
    is_incomplete = False
    if len(valid_rows) < 25:
        msg = f"WARNING: Onvolledige gegevens in {filename}: slechts {len(valid_rows)} dagen met metingen gevonden"
        WARNINGS.append(msg)
        is_incomplete = True
        
    last_tot = valid_rows[-1][1]
    
    if has_anomaly:
        # Fallback calculation: sum E-Today values that are <= 50.0
        clean_sum = sum(tod for _, _, tod in valid_rows if tod <= 50.0)
        production = int(clean_sum)
    else:
        # Standard historical formula
        first_tot = valid_rows[0][1]
        first_tod = valid_rows[0][2]
        production = int(last_tot) - (int(first_tot) - int(first_tod))
        
    return production, int(last_tot), is_incomplete

def main():
    args = parse_args()
    
    if args.version:
        try:
            build_time_str = datetime.fromtimestamp(os.path.getmtime(__file__)).strftime('%d-%m-%Y %H:%M:%S')
        except Exception:
            build_time_str = "04-07-2026 21:25:23"
        print(f"html-sbeam 2.0 ({build_time_str})")
        return
        
    # Determine config file (support both positional and optional)
    config_path = args.config_file if args.config_file is not None else args.config
    cfg = load_config(config_path)
    
    input_dir_raw = os.path.expandvars(cfg.get("INPUT_DIR", "")).strip()
    if not input_dir_raw or input_dir_raw == ".":
        input_dir = os.getcwd()
    else:
        input_dir = os.path.normpath(input_dir_raw.replace("\\", "/"))
        
    output_dir_raw = os.path.expandvars(cfg.get("OUTPUT_DIR", "")).strip()
    if not output_dir_raw or output_dir_raw == ".":
        output_dir = os.getcwd()
    else:
        output_dir = os.path.normpath(output_dir_raw.replace("\\", "/"))
        
    index_file = cfg["INDEX_FILE"]
    
    cfg_log_file = os.path.expandvars(cfg.get("LOG_FILE", "html-sbeam.log")).strip()
    if Path(cfg_log_file).is_absolute():
        log_path = os.path.normpath(cfg_log_file.replace("\\", "/"))
    elif sys.platform.startswith("linux"):
        log_dir = Path.home() / "log"
        log_dir.mkdir(parents=True, exist_ok=True)
        log_path = str(log_dir / cfg_log_file)
    else:
        log_path = str(SCRIPT_DIR / cfg_log_file)
        
    version = cfg["VERSION"]
    fface = cfg["FFACE"]
    fsize = cfg["FSIZE"]
    hostname = cfg["HOSTNAME"]
    title = cfg["TITLE"]
    icon_file = cfg["ICON"]
    footer_tmpl = cfg.get("FOOTER", _default_footer)
    
    output_file = os.path.join(output_dir, index_file)
    
    os.makedirs(output_dir, exist_ok=True)
    
    # Log messages capturing
    log_messages = []
    
    def log(msg):
        print(msg)
        log_messages.append(msg)
        
    log(f"SunnyBEAM Kleurgecodeerde HTML-generator v{version}")
    log(f"Inputmap: {input_dir}")
    log(f"Outputmap: {output_dir}")
    log(f"HTML-bestand: {output_file}")
    log(f"Logbestand: {log_path}")
    
    # Compile step (skipped if --proc / -p / --www is specified)
    if not args.proc_only:
        compile_monthly_files(input_dir, log, file_filter=args.filter)
        
    # Altijd de laatste 5 dagbestanden controleren en verwerken (voor automatische updates).
    # Als -j / --json is opgegeven, verwerken we alle dagbestanden.
    generate_daily_json_files(input_dir, output_dir, log, all_files=args.generate_json)
        
    global_min_time = "05:00"
    global_max_time = "22:30"
    
    # Laad het maximale vermogen voor de Y-as
    max_power_path = os.path.join(output_dir, "daily", "max_power.txt")
    global_max_power = 0.0
    if os.path.exists(max_power_path):
        try:
            with open(max_power_path, "r", encoding="utf-8") as f:
                global_max_power = float(f.read().strip())
        except Exception:
            pass
    
    if not args.proc_only and args.days:
        log("Alleen compilatie uitgevoerd (--days). HTML-generatie overgeslagen.")
        with open(log_path, "w", encoding="utf-8") as lf:
            lf.write("\n".join(log_messages))
        return

            
    # HTML generation step (skipped if --days / -d is specified)
    # Compile and copy CSS file to output directory
    css_src = SCRIPT_DIR / "html-sbeam.css"
    css_dst = Path(output_dir) / "html-sbeam.css"
    if css_src.exists():
        try:
            with open(css_src, "r", encoding="utf-8") as f:
                css_content = f.read()
            # Replace sizing variables
            css_content = css_content.replace("${SIZE_MOBILE}", cfg.get("SIZE_MOBILE", "0.9em"))
            css_content = css_content.replace("${SIZE_DESKTOP}", cfg.get("SIZE_DESKTOP", "1.25em"))
            with open(css_dst, "w", encoding="utf-8") as f:
                f.write(css_content)
            log(f"CSS-bestand gegenereerd en gekopieerd naar: {css_dst}")
        except Exception as e:
            log(f"Fout bij het genereren van CSS-bestand: {e}")
    else:
        log("Waarschuwing: html-sbeam.css niet gevonden in de scriptmap.")

    # Copy icon file to output directory
    icon_src = SCRIPT_DIR / icon_file
    icon_dst = Path(output_dir) / icon_file
    if icon_src.exists():
        try:
            shutil.copy2(icon_src, icon_dst)
            log(f"Icoon-bestand gekopieerd naar: {icon_dst}")
        except Exception as e:
            log(f"Fout bij het kopiëren van icoon-bestand: {e}")
    else:
        log(f"Waarschuwing: Icoon-bestand {icon_file} niet gevonden in de scriptmap.")

    log("Scannen naar maandelijkse gegevensbestanden...")
    
    # Look for compiled files first
    compiled_files = glob.glob(os.path.join(input_dir, "_[0-9][0-9][0-9][0-9]-[0-9][0-9].CSV"))
    # Look for raw files
    raw_files = glob.glob(os.path.join(input_dir, "[0-9][0-9][0-9][0-9]-[0-9][0-9].CSV"))
    
    # Merge, prioritizing compiled files
    files_to_process = {}
    
    # Populate with raw files first
    for fpath in raw_files:
        fname = os.path.basename(fpath)
        m = re.match(r"^(\d{4})-(\d{2})\.CSV$", fname)
        if m:
            month_str = m.group(0)
            if args.filter and (args.filter not in month_str and args.filter not in fname):
                continue
            files_to_process[month_str] = fpath
            
    # Overwrite with compiled files
    for fpath in compiled_files:
        fname = os.path.basename(fpath)
        m = re.match(r"^_(?P<month_str>\d{4}-\d{2})\.CSV$", fname)
        if m:
            month_str = m.group("month_str")
            target_key = month_str + ".CSV"
            if args.filter and (args.filter not in month_str and args.filter not in fname):
                continue
            files_to_process[target_key] = fpath
            
    log(f"{len(files_to_process)} unieke maanden gevonden om te verwerken.")
    
    monthly_data = {}  # (year, month) -> production
    yearly_gr_ttl = {}  # year -> last total
    incomplete_months = set()  # set of (year, month) tuples
    available_dates = {}  # YYYY -> MM -> list of DD
    
    now = datetime.now()
    
    for fname, fpath in sorted(files_to_process.items()):
        # Extract year and month
        m = re.match(r"^(\d{4})-(\d{2})\.CSV$", fname)
        if not m:
            continue
        year = int(m.group(1))
        month = int(m.group(2))
        
        is_current = (year == now.year and month == now.month)
        
        data_rows = parse_csv_file(fpath)
        
        # Bouw de datum-index voor de daggrafiek dropdowns op uit de maandelijkse rijen
        for date_str, _, _ in data_rows:
            parts = date_str.split('-')
            if len(parts) == 3:
                d_str, m_str, y_str = parts
                if y_str not in available_dates:
                    available_dates[y_str] = {}
                if m_str not in available_dates[y_str]:
                    available_dates[y_str][m_str] = []
                if d_str not in available_dates[y_str][m_str]:
                    available_dates[y_str][m_str].append(d_str)
                    
        production, last_tot, is_incomplete = calculate_monthly_production(data_rows, os.path.basename(fpath), is_current)
        
        if production is not None:
            log(f"  Verwerken: {os.path.basename(fpath)} -> {production} kWh (metingen: {len(data_rows)}, eindstand: {last_tot})")
            monthly_data[(year, month)] = production
            yearly_gr_ttl[year] = last_tot
            if is_incomplete:
                incomplete_months.add((year, month))
        else:
            log(f"  Verwerken: {os.path.basename(fpath)} -> Geen geldige gegevens gevonden.")

    if not monthly_data:
        log("Fout: Geen gegevens gevonden in de bestanden. HTML-generatie afgebroken.")
        with open(log_path, "w", encoding="utf-8") as lf:
            lf.write("\n".join(log_messages))
        return
        
    # Sorteer de dagen binnen elke maand in de datum-index
    for y in available_dates:
        for m in available_dates[y]:
            available_dates[y][m].sort()
            
    all_years = sorted(list(set(y for y, m in monthly_data.keys())))
    
    # Compute yearly totals (Y.ttl) derived from gr.ttl
    yearly_y_ttl = {}
    for i, year in enumerate(all_years):
        gr_ttl = yearly_gr_ttl.get(year)
        if gr_ttl is not None:
            # Find the closest previous year that has a valid gr.ttl
            prev_gr_ttl = None
            for prev_yr in reversed(all_years[:i]):
                if prev_yr in yearly_gr_ttl:
                    prev_gr_ttl = yearly_gr_ttl[prev_yr]
                    break
            
            if prev_gr_ttl is not None:
                yearly_y_ttl[year] = gr_ttl - prev_gr_ttl
            else:
                # First year or no previous year with data
                yearly_y_ttl[year] = gr_ttl
                    
    # Generate HTML content
    html = []
    html.append("<HTML>")
    html.append("  <HEAD>")
    html.append(f"  <TITLE>{title}</TITLE>")
    html.append(f'  <META NAME="generator" content="html-sbeam.py v{version}" />')
    html.append(f'  <META NAME="up-date" content="{datetime.now().strftime("%Y-%m-%d-%H-%M-%S")}" />')
    html.append('  <LINK REL="stylesheet" HREF="html-sbeam.css" TYPE="text/css">')
    html.append(f'  <LINK REL="icon" HREF="{icon_file}" TYPE="image/jpg">')
    html.append('  <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>')
    html.append("  </HEAD>")
    html.append("  <BODY>")
    
    # Header and Legend
    html.append(f"    <H1>{title}</H1>")
    html.append("    <H2>Waarden in kWh</H2>")
    html.append('    <P><span class="kwh-green">&#9632; Groen</span> = hoger dan vorig jaar | <span class="kwh-orange">&#9632; Oranje</span> = lager | <span class="kwh-equal">&#9632; Blauw</span> = gelijk | <span class="kwh-pink">&#9632; Roze</span> = onvolledige maand</P>')
    html.append("    <HR>")
    
    # Table Start
    html.append("    <TABLE border=1>")
    
    # Header Row
    html.append("      <TR>")
    html.append("        <TH>YR/mn</TH>")
    for month in range(1, 13):
        html.append(f"        <TH>{month:02d}</TH>")
    html.append("        <TH>Y.ttl</TH>")
    html.append("        <TH>Gr.ttl</TH>")
    html.append("      </TR>")
    
    # Data Rows
    for year in all_years:
        html.append("      <TR>")
        html.append(f"        <TD>{year}</TD>")
        
        for month in range(1, 13):
            val = monthly_data.get((year, month))
            val_str = str(val) if val is not None else ""
            
            # Year-over-year comparison for color coding
            prev_val = monthly_data.get((year - 1, month))
            
            color_class = ""
            if (year, month) in incomplete_months:
                color_class = " class='kwh-pink'"
            elif val is not None and prev_val is not None:
                if val > prev_val:
                    color_class = " class='kwh-green'"
                elif val < prev_val:
                    color_class = " class='kwh-orange'"
                else:
                    color_class = " class='kwh-equal'"
            elif val is not None:
                color_class = " class='kwh-neutral'"
                
            html.append(f"      <TD{color_class}>{val_str}</TD>")
            
        # Yearly totals
        y_ttl = yearly_y_ttl.get(year, "")
        gr_ttl = yearly_gr_ttl.get(year, "")
        
        html.append(f"      <TD>{y_ttl}</TD>")
        html.append(f"      <TD>{gr_ttl}</TD>")
        html.append("      </TR>")
        
    html.append("    </TABLE>")
    html.append("    <HR>")
    
    # Generate line chart container
    html.append("    <H2>Grafiek per Jaar</H2>")
    html.append("    <div class='chart-container' style='position: relative; max-width: 1000px; margin: 20px 0;'>")
    html.append("        <canvas id='sbeamChart'></canvas>")
    html.append("    </div>")
    html.append("    <HR>")
    
    # Generate datasets JS array for Chart.js
    datasets_js = []
    for idx, year in enumerate(all_years):
        year_data = []
        pt_colors = []
        pt_radius = []
        
        # Distribute colors evenly across the color wheel
        hue = int((idx * 360 / max(1, len(all_years))) % 360)
        color = f"hsl({hue}, 70%, 50%)"
        
        for month in range(1, 13):
            val = monthly_data.get((year, month))
            year_data.append(str(val) if val is not None else "null")
            if (year, month) in incomplete_months:
                pt_colors.append("'#FFC0CB'")
                pt_radius.append("6")
            else:
                pt_colors.append(f"'{color}'")
                pt_radius.append("3")
            
        datasets_js.append(f"""            {{
                label: "{year}",
                data: [{", ".join(year_data)}],
                borderColor: "{color}",
                backgroundColor: "{color}",
                pointBackgroundColor: [{", ".join(pt_colors)}],
                pointBorderColor: [{", ".join(pt_colors)}],
                pointRadius: [{", ".join(pt_radius)}],
                borderWidth: 2,
                tension: 0.1,
                spanGaps: true
            }}""")
    
    # Calculate monthly averages over all years (excluding incomplete months)
    avg_data = []
    for month in range(1, 13):
        vals = []
        for year in all_years:
            if (year, month) not in incomplete_months:
                val = monthly_data.get((year, month))
                if val is not None:
                    vals.append(val)
        if vals:
            avg_val = sum(vals) / len(vals)
            avg_data.append(str(round(avg_val, 1)))
        else:
            avg_data.append("null")

    datasets_js.append(f"""            {{
                label: "Gemiddelde",
                data: [{", ".join(avg_data)}],
                borderColor: "#000000",
                borderDash: [5, 5],
                borderWidth: 3,
                tension: 0.1,
                pointRadius: 4,
                pointBackgroundColor: "#000000",
                spanGaps: true
            }}""")

    datasets_str = ",\n".join(datasets_js)
    
    # Append Chart.js initialization script
    html.append("    <script>")
    html.append("    const ctx = document.getElementById('sbeamChart').getContext('2d');")
    html.append("    const chart = new Chart(ctx, {")
    html.append("        type: 'line',")
    html.append("        data: {")
    html.append("            labels: ['Jan', 'Feb', 'Mrt', 'Apr', 'Mei', 'Jun', 'Jul', 'Aug', 'Sep', 'Okt', 'Nov', 'Dec'],")
    html.append(f"            datasets: [\n{datasets_str}\n            ]")
    html.append("        },")
    html.append("        options: {")
    html.append("            responsive: true,")
    html.append("            plugins: {")
    html.append("                legend: {")
    html.append("                    position: 'right',")
    html.append("                    onClick: function(e, legendItem, legend) {")
    html.append("                        const index = legendItem.datasetIndex;")
    html.append("                        const ci = legend.chart;")
    html.append("                        const isCtrl = e.native.ctrlKey || e.native.metaKey;")
    html.append("                        ")
    html.append("                        if (isCtrl) {")
    html.append("                            // Toggle only the clicked dataset")
    html.append("                            ci.setDatasetVisibility(index, !ci.isDatasetVisible(index));")
    html.append("                        } else {")
    html.append("                            let visibleYearsCount = 0;")
    html.append("                            ci.data.datasets.forEach((d, i) => {")
    html.append("                                if (d.label !== 'Gemiddelde' && ci.isDatasetVisible(i)) visibleYearsCount++;")
    html.append("                            });")
    html.append("                            const isSelfVisible = ci.isDatasetVisible(index);")
    html.append("                            const isGemiddelde = ci.data.datasets[index].label === 'Gemiddelde';")
    html.append("                            ")
    html.append("                            if (isGemiddelde) {")
    html.append("                                ci.setDatasetVisibility(index, !isSelfVisible);")
    html.append("                            } else {")
    html.append("                                if (visibleYearsCount === 1 && isSelfVisible) {")
    html.append("                                    ci.data.datasets.forEach((d, i) => {")
    html.append("                                        ci.setDatasetVisibility(i, true);")
    html.append("                                    });")
    html.append("                                } else {")
    html.append("                                    ci.data.datasets.forEach((d, i) => {")
    html.append("                                        if (d.label === 'Gemiddelde') {")
    html.append("                                            ci.setDatasetVisibility(i, true);")
    html.append("                                        } else {")
    html.append("                                            ci.setDatasetVisibility(i, i === index);")
    html.append("                                        }")
    html.append("                                    });")
    html.append("                                }")
    html.append("                            }")
    html.append("                        }")
    html.append("                        ci.update();")
    html.append("                    }")
    html.append("                },")
    html.append("                title: {")
    html.append("                    display: true,")
    html.append("                    text: 'Maandelijkse Opbrengst per Jaar (kWh)'")
    html.append("                }")
    html.append("            },")
    html.append("            scales: {")
    html.append("                y: {")
    html.append("                    beginAtZero: true,")
    html.append("                    title: {")
    html.append("                        display: true,")
    html.append("                        text: 'kWh'")
    html.append("                    }")
    html.append("                },")
    html.append("                x: {")
    html.append("                    title: {")
    html.append("                        display: true,")
    html.append("                        text: 'Maand'")
    html.append("                    }")
    html.append("                }")
    html.append("            }")
    html.append("        }")
    html.append("    });")
    html.append("    </script>")
    
    # Generate cumulative line chart container
    html.append("    <H2>Cumulatieve Opbrengst per Jaar</H2>")
    html.append("    <div class='chart-container' style='position: relative; max-width: 1000px; margin: 20px 0;'>")
    html.append("        <canvas id='sbeamCumChart'></canvas>")
    html.append("    </div>")
    html.append("    <HR>")
    
    # Generate cumulative datasets JS array for Chart.js
    datasets_cum_js = []
    for idx, year in enumerate(all_years):
        year_cum_data = []
        running_total = 0
        has_any_data = False
        for month in range(1, 13):
            val = monthly_data.get((year, month))
            if val is not None:
                running_total += val
                year_cum_data.append(str(running_total))
                has_any_data = True
            else:
                is_future = (year == now.year and month > now.month)
                if is_future:
                    year_cum_data.append("null")
                else:
                    if has_any_data:
                        year_cum_data.append(str(running_total))
                    else:
                        year_cum_data.append("null")
            
        # Distribute colors evenly across the color wheel
        hue = int((idx * 360 / max(1, len(all_years))) % 360)
        color = f"hsl({hue}, 70%, 50%)"
        
        datasets_cum_js.append(f"""            {{
                label: "{year}",
                data: [{", ".join(year_cum_data)}],
                borderColor: "{color}",
                backgroundColor: "{color}",
                borderWidth: 2,
                tension: 0.1,
                spanGaps: true
            }}""")
    
    # Calculate cumulative averages from the monthly average values
    cum_avg_data = []
    running_avg_total = 0.0
    for avg_val_str in avg_data:
        if avg_val_str != "null":
            running_avg_total += float(avg_val_str)
            cum_avg_data.append(str(round(running_avg_total, 1)))
        else:
            cum_avg_data.append("null")

    datasets_cum_js.append(f"""            {{
                label: "Gemiddelde",
                data: [{", ".join(cum_avg_data)}],
                borderColor: "#000000",
                borderDash: [5, 5],
                borderWidth: 3,
                tension: 0.1,
                pointRadius: 4,
                pointBackgroundColor: "#000000",
                spanGaps: true
            }}""")

    datasets_cum_str = ",\n".join(datasets_cum_js)
    
    # Append Chart.js initialization script for cumulative chart
    html.append("    <script>")
    html.append("    const ctxCum = document.getElementById('sbeamCumChart').getContext('2d');")
    html.append("    const chartCum = new Chart(ctxCum, {")
    html.append("        type: 'line',")
    html.append("        data: {")
    html.append("            labels: ['Jan', 'Feb', 'Mrt', 'Apr', 'Mei', 'Jun', 'Jul', 'Aug', 'Sep', 'Okt', 'Nov', 'Dec'],")
    html.append(f"            datasets: [\n{datasets_cum_str}\n            ]")
    html.append("        },")
    html.append("        options: {")
    html.append("            responsive: true,")
    html.append("            plugins: {")
    html.append("                legend: {")
    html.append("                    position: 'right',")
    html.append("                    onClick: function(e, legendItem, legend) {")
    html.append("                        const index = legendItem.datasetIndex;")
    html.append("                        const ci = legend.chart;")
    html.append("                        const isCtrl = e.native.ctrlKey || e.native.metaKey;")
    html.append("                        ")
    html.append("                        if (isCtrl) {")
    html.append("                            ci.setDatasetVisibility(index, !ci.isDatasetVisible(index));")
    html.append("                        } else {")
    html.append("                            let visibleYearsCount = 0;")
    html.append("                            ci.data.datasets.forEach((d, i) => {")
    html.append("                                if (d.label !== 'Gemiddelde' && ci.isDatasetVisible(i)) visibleYearsCount++;")
    html.append("                            });")
    html.append("                            const isSelfVisible = ci.isDatasetVisible(index);")
    html.append("                            const isGemiddelde = ci.data.datasets[index].label === 'Gemiddelde';")
    html.append("                            ")
    html.append("                            if (isGemiddelde) {")
    html.append("                                ci.setDatasetVisibility(index, !isSelfVisible);")
    html.append("                            } else {")
    html.append("                                if (visibleYearsCount === 1 && isSelfVisible) {")
    html.append("                                    ci.data.datasets.forEach((d, i) => {")
    html.append("                                        ci.setDatasetVisibility(i, true);")
    html.append("                                    });")
    html.append("                                } else {")
    html.append("                                    ci.data.datasets.forEach((d, i) => {")
    html.append("                                        if (d.label === 'Gemiddelde') {")
    html.append("                                            ci.setDatasetVisibility(i, true);")
    html.append("                                        } else {")
    html.append("                                            ci.setDatasetVisibility(i, i === index);")
    html.append("                                        }")
    html.append("                                    });")
    html.append("                                }")
    html.append("                            }")
    html.append("                        }")
    html.append("                        ci.update();")
    html.append("                    }")
    html.append("                },")
    html.append("                title: {")
    html.append("                    display: true,")
    html.append("                    text: 'Cumulatieve Jaaropbrengst (kWh)'")
    html.append("                }")
    html.append("            },")
    html.append("            scales: {")
    html.append("                y: {")
    html.append("                    beginAtZero: true,")
    html.append("                    title: {")
    html.append("                        display: true,")
    html.append("                        text: 'kWh'")
    html.append("                    }")
    html.append("                },")
    html.append("                x: {")
    html.append("                    title: {")
    html.append("                        display: true,")
    html.append("                        text: 'Maand'")
    html.append("                    }")
    html.append("                }")
    html.append("            }")
    html.append("        }")
    html.append("    });")
    html.append("    </script>")
    
    # 4th Screen: Daily time series chart
    html.append("    <H2>Historisch verloop gedurende de dag</H2>")
    svg_left = '<svg width="1em" height="1em" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="3.5" stroke-linecap="round" stroke-linejoin="round" style="display: inline-block; vertical-align: middle;"><line x1="19" y1="12" x2="5" y2="12"></line><polyline points="12 19 5 12 12 5"></polyline></svg>'
    svg_right = '<svg width="1em" height="1em" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="3.5" stroke-linecap="round" stroke-linejoin="round" style="display: inline-block; vertical-align: middle;"><line x1="5" y1="12" x2="19" y2="12"></line><polyline points="12 5 19 12 12 19"></polyline></svg>'
    html.append("    <div class='select-container' style='margin: 15px 0; display: flex; gap: 10px; align-items: center; font-size: 0.95em; flex-wrap: wrap;'>")
    html.append(f"        <button id='prevDay' class='nav-btn prev-btn'>{svg_left}</button>")
    html.append("        <div style='display: flex; gap: 8px; align-items: center; flex-wrap: wrap;'>")
    html.append("            <label for='selectYear'>Jaar:</label>")
    html.append("            <select id='selectYear'></select>")
    html.append("            <label for='selectMonth'>Maand:</label>")
    html.append("            <select id='selectMonth'></select>")
    html.append("            <label for='selectDay'>Dag:</label>")
    html.append("            <select id='selectDay'></select>")
    html.append("        </div>")
    html.append(f"        <button id='nextDay' class='nav-btn next-btn'>{svg_right}</button>")
    html.append("    </div>")
    html.append("    <div class='chart-container' style='position: relative; max-width: 1000px; margin: 20px 0;'>")
    html.append("        <canvas id='sbeamDailyChart'></canvas>")
    html.append("    </div>")
    html.append("    <HR>")
    
    # JavaScript logic for daily chart
    available_dates_json = json.dumps(available_dates)
    html.append("    <script>")
    html.append(f"    const availableDates = {available_dates_json};")
    html.append(f"    const globalMinTime = '{global_min_time}';")
    html.append(f"    const globalMaxTime = '{global_max_time}';")
    html.append(f"    const globalMaxPower = {global_max_power};")
    html.append("    const selectYear = document.getElementById('selectYear');")
    html.append("    const selectMonth = document.getElementById('selectMonth');")
    html.append("    const selectDay = document.getElementById('selectDay');")
    html.append("    const prevBtn = document.getElementById('prevDay');")
    html.append("    const nextBtn = document.getElementById('nextDay');")
    html.append("    let dailyChart = null;")
    html.append("    let allDates = [];")
    html.append("")
    html.append("    function buildAllDates() {")
    html.append("        allDates = [];")
    html.append("        const years = Object.keys(availableDates).sort((a, b) => a - b);")
    html.append("        years.forEach(y => {")
    html.append("            const months = Object.keys(availableDates[y]).sort((a, b) => a - b);")
    html.append("            months.forEach(m => {")
    html.append("                const days = [...availableDates[y][m]].sort((a, b) => parseInt(a, 10) - parseInt(b, 10));")
    html.append("                days.forEach(d => {")
    html.append("                    allDates.push({ year: y, month: m, day: d });")
    html.append("                });")
    html.append("            });")
    html.append("        });")
    html.append("    }")
    html.append("")
    html.append("    function getCurrentDateIndex() {")
    html.append("        const y = selectYear.value;")
    html.append("        const m = selectMonth.value;")
    html.append("        const d = selectDay.value;")
    html.append("        return allDates.findIndex(item => item.year === y && item.month === m && item.day === d);")
    html.append("    }")
    html.append("")
    html.append("    function updateNavButtons() {")
    html.append("        const idx = getCurrentDateIndex();")
    html.append("        prevBtn.disabled = (idx <= 0);")
    html.append("        nextBtn.disabled = (idx === -1 || idx >= allDates.length - 1);")
    html.append("    }")
    html.append("")
    html.append("    function timeToMinutes(tStr) {")
    html.append("        const parts = tStr.split(':');")
    html.append("        return parseInt(parts[0], 10) * 60 + parseInt(parts[1], 10);")
    html.append("    }")
    html.append("")
    html.append("    function minutesToTime(mins) {")
    html.append("        const h = Math.floor(mins / 60);")
    html.append("        const m = mins % 60;")
    html.append("        return `${h.toString().padStart(2, '0')}:${m.toString().padStart(2, '0')}`;")
    html.append("    }")
    html.append("")
    html.append("    function generateTimeLabels(minStr, maxStr) {")
    html.append("        const labels = [];")
    html.append("        let curr = timeToMinutes(minStr);")
    html.append("        const end = timeToMinutes(maxStr);")
    html.append("        while (curr <= end) {")
    html.append("            labels.push(minutesToTime(curr));")
    html.append("            curr += 10;")
    html.append("        }")
    html.append("        return labels;")
    html.append("    }")
    html.append("")
    html.append("    const fixedLabels = generateTimeLabels(globalMinTime, globalMaxTime);")
    html.append("")
    html.append("    function initDropdowns() {")
    html.append("        buildAllDates();")
    html.append("        const years = Object.keys(availableDates).sort((a, b) => b - a);")
    html.append("        selectYear.innerHTML = years.map(y => `<option value='${y}'>${y}</option>`).join('');")
    html.append("        selectYear.addEventListener('change', () => updateMonths());")
    html.append("        selectMonth.addEventListener('change', () => updateDays());")
    html.append("        selectDay.addEventListener('change', () => loadDailyData());")
    html.append("        ")
    html.append("        prevBtn.addEventListener('click', () => {")
    html.append("            const idx = getCurrentDateIndex();")
    html.append("            if (idx > 0) {")
    html.append("                const target = allDates[idx - 1];")
    html.append("                selectYear.value = target.year;")
    html.append("                updateMonths(target.month, target.day);")
    html.append("            }")
    html.append("        });")
    html.append("        ")
    html.append("        nextBtn.addEventListener('click', () => {")
    html.append("            const idx = getCurrentDateIndex();")
    html.append("            if (idx !== -1 && idx < allDates.length - 1) {")
    html.append("                const target = allDates[idx + 1];")
    html.append("                selectYear.value = target.year;")
    html.append("                updateMonths(target.month, target.day);")
    html.append("            }")
    html.append("        });")
    html.append("        ")
    html.append("        updateMonths();")
    html.append("    }")
    html.append("")
    html.append("    function updateMonths(targetMonth = null, targetDay = null) {")
    html.append("        const year = selectYear.value;")
    html.append("        const months = Object.keys(availableDates[year] || {}).sort((a, b) => b - a);")
    html.append("        selectMonth.innerHTML = months.map(m => `<option value='${m}'>${m}</option>`).join('');")
    html.append("        if (targetMonth && months.includes(targetMonth)) {")
    html.append("            selectMonth.value = targetMonth;")
    html.append("        }")
    html.append("        updateDays(targetDay);")
    html.append("    }")
    html.append("")
    html.append("    function updateDays(targetDay = null) {")
    html.append("        const year = selectYear.value;")
    html.append("        const month = selectMonth.value;")
    html.append("        const days = (availableDates[year] && availableDates[year][month]) || [];")
    html.append("        const sortedDays = [...days].sort((a, b) => parseInt(a, 10) - parseInt(b, 10));")
    html.append("        selectDay.innerHTML = sortedDays.map(d => `<option value='${d}'>${d}</option>`).join('');")
    html.append("        if (sortedDays.length > 0) {")
    html.append("            if (targetDay && sortedDays.includes(targetDay)) {")
    html.append("                selectDay.value = targetDay;")
    html.append("            } else {")
    html.append("                selectDay.value = sortedDays[sortedDays.length - 1];")
    html.append("            }")
    html.append("        }")
    html.append("        loadDailyData();")
    html.append("    }")
    html.append("")
    html.append("    function loadDailyData() {")
    html.append("        const year = selectYear.value;")
    html.append("        const month = selectMonth.value;")
    html.append("        const day = selectDay.value;")
    html.append("        if (!year || !month || !day) return;")
    html.append("        const filename = `daily/${year}-${month}-${day}.json`;")
    html.append("        fetch(filename)")
    html.append("            .then(res => {")
    html.append("                if (!res.ok) throw new Error('Gegevens niet gevonden');")
    html.append("                return res.json();")
    html.append("            })")
    html.append("            .then(data => {")
    html.append("                const alignedValues = fixedLabels.map(label => {")
    html.append("                    const idx = data.labels.indexOf(label);")
    html.append("                    return idx !== -1 ? data.data[idx] : null;")
    html.append("                });")
    html.append("                renderDailyChart(alignedValues, `${day}-${month}-${year}`);")
    html.append("                updateNavButtons();")
    html.append("            })")
    html.append("            .catch(err => {")
    html.append("                const emptyValues = fixedLabels.map(() => null);")
    html.append("                renderDailyChart(emptyValues, `Geen gegevens voor ${day}-${month}-${year}`);")
    html.append("                updateNavButtons();")
    html.append("            });")
    html.append("    }")
    html.append("")
    html.append("    function renderDailyChart(values, dateLabel) {")
    html.append("        const ctx = document.getElementById('sbeamDailyChart').getContext('2d');")
    html.append("        if (dailyChart) {")
    html.append("            dailyChart.data.datasets[0].data = values;")
    html.append("            dailyChart.options.plugins.title.text = `Vermogensverloop op ${dateLabel} (10-minutenwaarden in kW)`;")
    html.append("            dailyChart.update();")
    html.append("        } else {")
    html.append("            dailyChart = new Chart(ctx, {")
    html.append("                type: 'line',")
    html.append("                data: {")
    html.append("                    labels: fixedLabels,")
    html.append("                    datasets: [{")
    html.append("                        label: 'Vermogen (kW)',")
    html.append("                        data: values,")
    html.append("                        borderColor: '#FF9800',")
    html.append("                        backgroundColor: 'rgba(255, 152, 0, 0.15)',")
    html.append("                        borderWidth: 2.5,")
    html.append("                        tension: 0.35,")
    html.append("                        fill: true,")
    html.append("                        pointRadius: 1,")
    html.append("                        pointHoverRadius: 5")
    html.append("                    }]")
    html.append("                },")
    html.append("                options: {")
    html.append("                    responsive: true,")
    html.append("                    plugins: {")
    html.append("                        legend: { display: false },")
    html.append("                        title: {")
    html.append("                            display: true,")
    html.append("                            text: `Vermogensverloop op ${dateLabel} (10-minutenwaarden in kW)`,")
    html.append("                            font: { size: 14 }")
    html.append("                        }")
    html.append("                    },")
    html.append("                    scales: {")
    html.append("                        y: {")
    html.append("                            beginAtZero: true,")
    html.append("                            max: globalMaxPower > 0 ? Math.ceil(globalMaxPower * 2) / 2 : undefined,")
    html.append("                            title: { display: true, text: 'kW' }")
    html.append("                        },")
    html.append("                        x: {")
    html.append("                            title: { display: true, text: 'Tijd' }")
    html.append("                        }")
    html.append("                    }")
    html.append("                }")
    html.append("            });")
    html.append("        }")
    html.append("    }")
    html.append("")
    html.append("    // Mobiele detectie om de selectie-knoppen te vergroten naar 110px.")
    html.append("    // Dit compenseert voor het feit dat we GEEN viewport-tag gebruiken (om tabel/grafiekverhoudingen intact te houden)")
    html.append("    // waardoor de browser de pagina standaard uitzoomt en knoppen anders te klein worden op het scherm.")
    html.append("    if (/Mobi|Android|iPhone|iPad/i.test(navigator.userAgent)) {")
    html.append("        document.body.classList.add('is-mobile');")
    html.append("    }")
    html.append("    initDropdowns();")
    html.append("    </script>")

    # Format date and time
    now_dt = datetime.now()
    date_str = now_dt.strftime("%d-%m-%Y")
    time_str = now_dt.strftime("%H:%M")

    # Get build time of the script file dynamically
    try:
        build_time_str = datetime.fromtimestamp(os.path.getmtime(__file__)).strftime('%d-%m-%Y %H:%M')
    except Exception:
        build_time_str = now_dt.strftime('%d-%m-%Y %H:%M')
        
    process_time_str = now_dt.strftime('%a %b %d %H:%M:%S %Z %Y')
    
    # === START FOOTER VERVANGING ===
    footer_tmpl = cfg.get("FOOTER", _default_footer)
    footer_text = footer_tmpl
    pgm_link = f'<a href="https://github.com/agrarix/{PGM}">{PGM}</a>'
    footer_text = footer_text.replace("${PGM}", pgm_link).replace("{PGM}", pgm_link)
    footer_text = footer_text.replace("${VER}", VERSION).replace("{VER}", VERSION).replace("{VERSION}", VERSION)
    footer_text = footer_text.replace("${DATE}", date_str).replace("{date_str}", date_str)
    footer_text = footer_text.replace("${TIME}", time_str).replace("{time_str}", time_str)
    if sys.platform != "win32":
        footer_text = footer_text.replace("(${OS})", f"(Linux) at {_hostname}").replace("({OS})", f"(Linux) at {_hostname}")
        if f"(Linux) at" not in footer_text:
            footer_text = footer_text.replace("(Linux)", f"(Linux) at {_hostname}")
    footer_text = footer_text.replace("${OS}", _os_naam).replace("{OS}", _os_naam)
    footer_text = footer_text.replace("${HOSTNAME}", _hostname).replace("{HOSTNAME}", _hostname)
    # === END FOOTER VERVANGING ===
    
    html.append("    <center>")
    html.append(f"    <div class=\"footer\">{footer_text}</div>")
    html.append("    </center>")
    html.append("  </BODY>")
    html.append("</HTML>")
    
    # Write HTML output
    with open(output_file, "w", encoding="utf-8") as f:
        f.write("\n".join(html))
    log(f"Bestand met succes gegenereerd op: {output_file}")
    
    # Output warnings summary at the end
    if WARNINGS:
        log("\n" + "=" * 80)
        log("SAMENVATTING VAN ANOMALIEËN / WAARSCHUWINGEN:")
        log("=" * 80)
        for w in WARNINGS:
            log(w)
        log("=" * 80 + "\n")
    else:
        log("\nGeen anomalieën of waarschuwingen gedetecteerd.\n")
        
    # Write log file
    with open(log_path, "w", encoding="utf-8") as lf:
        lf.write("\n".join(log_messages))

if __name__ == "__main__":
    main()
